/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * Last synced: 2026-05-16 — includes CausalPredictionOut from GET /api/v1/causal/prediction.
 * Regenerate with: pnpm generate:api  (requires Node + pnpm in PATH)
 */


export interface paths {
  "/health": {
    /**
     * Liveness probe
     * @description Always returns 200 when the process is alive.
     */
    get: operations["getHealth"];
  };
  "/ready": {
    /**
     * Readiness probe
     * @description Returns 200 when the backend is ready to serve real traffic — DB
     * connection up, the configured predictor model is loaded, and the
     * most recent migration is applied. 503 otherwise.
     */
    get: operations["getReady"];
  };
  "/api/v1/sessions": {
    /** List sessions present in the database */
    get: operations["listSessions"];
  };
  "/api/v1/sessions/{session_id}/snapshot": {
    /**
     * Current engine state for an active replay
     * @description Returns the in-memory `RaceState` for the session that is
     * currently being replayed. 404 if there is no active replay for
     * the requested `session_id`.
     */
    get: operations["getSessionSnapshot"];
  };
  "/api/v1/replay/start": {
    /**
     * Start a replay of a historical session
     * @description Boots the `ReplayFeed` against the requested session and begins
     * emitting events to the engine. Only one replay may run at a
     * time in V1; calling this while a replay is active returns 409.
     */
    post: operations["startReplay"];
  };
  "/api/v1/replay/stop": {
    /**
     * Stop the active replay
     * @description Idempotent. Returns 200 even if no replay was running.
     */
    post: operations["stopReplay"];
  };
  "/api/v1/degradation": {
    /** Fitted degradation curve for a circuit + compound */
    get: operations["getDegradationCurve"];
  };
  "/api/v1/backtest/{session_id}": {
    /** Engine alerts vs known undercuts for a session */
    get: operations["getBacktestResult"];
  };
  "/api/v1/config/predictor": {
    /**
     * Switch the active pace predictor at runtime
     * @description Switches `PacePredictor` between `scipy` and `xgboost` without
     * restarting the backend. The new predictor takes effect on the
     * next `lap_complete` processed by the engine. 409 if the
     * requested predictor's model is not loaded (e.g. `xgboost`
     * before `make train-xgb` has run).
     */
    post: operations["setActivePredictor"];
  };
  "/api/v1/causal/prediction": {
    /**
     * Causal undercut viability prediction for one driver pair at one lap
     * @description Constructs RaceState and DriverState from query parameters
     * and evaluates the causal live-inference chain. Read-only — does
     * not alter live engine alerts or WebSocket state.
     */
    get: operations["getCausalPrediction"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description Tyre compound identifier. Values match
     * `pitwall.engine.projection.Compound` and the CHECK constraints
     * in `db_schema_v1.sql`.
     *
     * @enum {string}
     */
    Compound: "SOFT" | "MEDIUM" | "HARD" | "INTER" | "WET";
    /** @enum {string} */
    PredictorName: "scipy" | "xgboost";
    /** @enum {string} */
    TrackStatus: "GREEN" | "SC" | "VSC" | "YELLOW" | "RED";
    /**
     * @description See `websocket_messages.md` for the meaning of each value and
     * the conditions under which the engine emits it.
     *
     * @enum {string}
     */
    AlertType: "UNDERCUT_VIABLE" | "UNDERCUT_RISK" | "UNDERCUT_DISABLED_RAIN" | "SUSPENDED_SC" | "SUSPENDED_VSC" | "INSUFFICIENT_DATA";
    Health: {
      /** @example ok */
      status: string;
      /** @example 0.1.0 */
      version: string;
    };
    /**
     * @description FastAPI's default error envelope. Kept minimal in V1; can be
     * upgraded to RFC 7807 (`type`, `title`, `status`) without
     * breaking clients because `detail` is preserved.
     */
    Problem: {
      /** @example Session 'monaco_2024_R' not found. */
      detail: string | Record<string, never>[];
    };
    SessionSummary: {
      /** @example monaco_2024_R */
      session_id: string;
      /** @example monaco */
      circuit_id: string;
      /** @example 2024 */
      season: number;
      /** @example 8 */
      round_number: number;
      /** Format: date */
      date: string;
      /** @example 78 */
      total_laps?: number | null;
    };
    DriverState: {
      /** @example VER */
      driver_code: string;
      /** @example RBR */
      team_code?: string | null;
      /** @example 1 */
      position: number;
      /** @example 0 */
      gap_to_leader_ms?: number | null;
      /** @example null */
      gap_to_ahead_ms?: number | null;
      /** @example 74521 */
      last_lap_ms?: number | null;
      compound: components["schemas"]["Compound"];
      /** @example 18 */
      tyre_age: number;
      is_in_pit: boolean;
      is_lapped: boolean;
      last_pit_lap?: number | null;
      /** @example 1 */
      stint_number: number;
      /**
       * Format: float
       * @description Score `[0, 1]` of the undercut opportunity towards the
       * driver immediately ahead. `null` if no relevant pair (e.g.
       * this driver leads the race or is lapped).
       */
      undercut_score?: number | null;
    };
    RaceSnapshot: {
      session_id: string;
      current_lap: number;
      track_status: components["schemas"]["TrackStatus"];
      /** Format: float */
      track_temp_c?: number | null;
      /** Format: float */
      air_temp_c?: number | null;
      /** Format: float */
      humidity_pct?: number | null;
      drivers: components["schemas"]["DriverState"][];
      active_predictor: components["schemas"]["PredictorName"];
      /** Format: date-time */
      last_event_ts: string;
    };
    DegradationCurve: {
      circuit_id: string;
      compound: components["schemas"]["Compound"];
      /**
       * @description Quadratic coefficients of the model
       * `lap_time_ms(t) = a + b·t + c·t²` where `t = tyre_age`.
       */
      coefficients: {
        /**
         * Format: double
         * @example 74500
         */
        a: number;
        /**
         * Format: double
         * @example 120
         */
        b: number;
        /**
         * Format: double
         * @example 5
         */
        c: number;
      };
      /** Format: float */
      r_squared?: number | null;
      /** @example 412 */
      n_samples: number;
      /** @description Optional raw points for plotting. */
      sample_points?: {
          tyre_age: number;
          lap_time_ms: number;
        }[];
    };
    ReplayStartRequest: {
      /** @example monaco_2024_R */
      session_id: string;
      /**
       * Format: float
       * @description Wall-clock acceleration. `1` = real time, `1000` = test
       * mode. Implementation must process events in causal order;
       * see ``replay_event_format.md`` § ordering.
       *
       * @default 30
       */
      speed_factor?: number;
    };
    ReplayRun: {
      /** Format: uuid */
      run_id: string;
      session_id: string;
      /** Format: float */
      speed_factor: number;
      /** Format: date-time */
      started_at: string;
      pace_predictor: components["schemas"]["PredictorName"];
    };
    ReplayStopResponse: {
      /**
       * @description `true` if a replay was running and has been stopped, `false`
       * if there was nothing to stop. Either way, the response
       * status is 200.
       */
      stopped: boolean;
      /** Format: uuid */
      run_id?: string | null;
    };
    SetPredictorRequest: {
      predictor: components["schemas"]["PredictorName"];
    };
    SetPredictorResponse: {
      active_predictor: components["schemas"]["PredictorName"];
    };
    UndercutMatch: {
      /** @example NOR */
      attacker: string;
      /** @example VER */
      defender: string;
      lap_alerted?: number | null;
      lap_actual?: number | null;
      was_successful?: boolean | null;
    };
    BacktestResult: {
      session_id: string;
      predictor: components["schemas"]["PredictorName"];
      /** Format: float */
      precision: number;
      /** Format: float */
      recall: number;
      /** Format: float */
      f1: number;
      /** Format: float */
      mean_lead_time_laps?: number | null;
      mae_k1_ms?: number | null;
      mae_k3_ms?: number | null;
      mae_k5_ms?: number | null;
      true_positives?: components["schemas"]["UndercutMatch"][];
      false_positives?: components["schemas"]["UndercutMatch"][];
      false_negatives?: components["schemas"]["UndercutMatch"][];
    };
    /** One counterfactual scenario from the causal undercut prediction. */
    CausalCounterfactualOut: {
      scenario_name: string;
      undercut_viable: boolean;
      required_gain_ms?: number | null;
      projected_gain_ms?: number | null;
      projected_gap_after_pit_ms?: number | null;
      main_limiting_factor: string;
      explanation: string;
    };
    /**
     * Causal undercut viability prediction for one driver pair.
     * @description Returned by GET /api/v1/causal/prediction.
     * support_level is one of: "strong", "weak", "insufficient".
     */
    CausalPredictionOut: {
      session_id: string;
      circuit_id: string;
      lap_number: number;
      attacker_code: string;
      defender_code: string;
      undercut_viable: boolean;
      /**
       * @description One of: "strong", "weak", "insufficient".
       * strong = R² ≥ 0.35; weak = R² ≥ 0.15; insufficient = below noise threshold.
       */
      support_level: string;
      /** Format: float */
      confidence: number;
      required_gain_ms?: number | null;
      projected_gain_ms?: number | null;
      projected_gap_after_pit_ms?: number | null;
      /** @description One of: "low", "medium", "high", "unknown". */
      traffic_after_pit: string;
      top_factors: string[];
      explanations: string[];
      counterfactuals: components["schemas"]["CausalCounterfactualOut"][];
    };
  };
  responses: never;
  parameters: {
    /** @example monaco_2024_R */
    SessionId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Liveness probe
   * @description Always returns 200 when the process is alive.
   */
  getHealth: {
    responses: {
      /** @description Process is alive. */
      200: {
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  /**
   * Readiness probe
   * @description Returns 200 when the backend is ready to serve real traffic — DB
   * connection up, the configured predictor model is loaded, and the
   * most recent migration is applied. 503 otherwise.
   */
  getReady: {
    responses: {
      /** @description Backend is ready. */
      200: {
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      /** @description Backend not ready. */
      503: {
        content: {
          "application/json": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** List sessions present in the database */
  listSessions: {
    responses: {
      /** @description OK. The list may be empty. */
      200: {
        content: {
          "application/json": components["schemas"]["SessionSummary"][];
        };
      };
    };
  };
  /**
   * Current engine state for an active replay
   * @description Returns the in-memory `RaceState` for the session that is
   * currently being replayed. 404 if there is no active replay for
   * the requested `session_id`.
   */
  getSessionSnapshot: {
    parameters: {
      path: {
        session_id: components["parameters"]["SessionId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RaceSnapshot"];
        };
      };
      /** @description No active replay for this session. */
      404: {
        content: {
          "application/json": components["schemas"]["Problem"];
        };
      };
    };
  };
  /**
   * Start a replay of a historical session
   * @description Boots the `ReplayFeed` against the requested session and begins
   * emitting events to the engine. Only one replay may run at a
   * time in V1; calling this while a replay is active returns 409.
   */
  startReplay: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReplayStartRequest"];
      };
    };
    responses: {
      /** @description Replay started. */
      202: {
        content: {
          "application/json": components["schemas"]["ReplayRun"];
        };
      };
      /** @description Malformed request body. */
      400: {
        content: {
          "application/json": components["schemas"]["Problem"];
        };
      };
      /** @description Session not found. */
      404: {
        content: {
          "application/json": components["schemas"]["Problem"];
        };
      };
      /** @description A replay is already running. */
      409: {
        content: {
          "application/json": components["schemas"]["Problem"];
        };
      };
    };
  };
  /**
   * Stop the active replay
   * @description Idempotent. Returns 200 even if no replay was running.
   */
  stopReplay: {
    responses: {
      /** @description OK. */
      200: {
        content: {
          "application/json": components["schemas"]["ReplayStopResponse"];
        };
      };
    };
  };
  /** Fitted degradation curve for a circuit + compound */
  getDegradationCurve: {
    parameters: {
      query: {
        /** @example monaco */
        circuit: string;
        /** @example MEDIUM */
        compound: components["schemas"]["Compound"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["DegradationCurve"];
        };
      };
      /** @description No fit available for this (circuit, compound). */
      404: {
        content: {
          "application/json": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Engine alerts vs known undercuts for a session */
  getBacktestResult: {
    parameters: {
      query?: {
        /**
         * @description Predictor to evaluate. Defaults to the active server-side
         * predictor.
         */
        predictor?: components["schemas"]["PredictorName"];
      };
      path: {
        session_id: components["parameters"]["SessionId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["BacktestResult"];
        };
      };
      /** @description Session not found, or no curated known-undercut list yet. */
      404: {
        content: {
          "application/json": components["schemas"]["Problem"];
        };
      };
    };
  };
  /**
   * Switch the active pace predictor at runtime
   * @description Switches `PacePredictor` between `scipy` and `xgboost` without
   * restarting the backend. The new predictor takes effect on the
   * next `lap_complete` processed by the engine. 409 if the
   * requested predictor's model is not loaded (e.g. `xgboost`
   * before `make train-xgb` has run).
   */
  setActivePredictor: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetPredictorRequest"];
      };
    };
    responses: {
      /** @description OK. Returns the now-active predictor. */
      200: {
        content: {
          "application/json": components["schemas"]["SetPredictorResponse"];
        };
      };
      /** @description Unknown predictor name. */
      400: {
        content: {
          "application/json": components["schemas"]["Problem"];
        };
      };
      /** @description Requested predictor is not loaded. */
      409: {
        content: {
          "application/json": components["schemas"]["Problem"];
        };
      };
    };
  };
  /**
   * Causal undercut viability prediction for one driver pair at one lap
   * @description Read-only causal inference. Does not alter live engine state.
   */
  getCausalPrediction: {
    parameters: {
      query?: {
        /** @example bahrain_2024_R */
        session_id?: string;
        /** @example bahrain */
        circuit_id?: string;
        /** @example 30 */
        lap_number?: number;
        total_laps?: number | null;
        /** @example NOR */
        attacker?: string;
        /** @example MEDIUM */
        attacker_compound?: string;
        /** @example 15 */
        attacker_tyre_age?: number;
        /** @example VER */
        defender?: string;
        /** @example HARD */
        defender_compound?: string;
        /** @example 25 */
        defender_tyre_age?: number;
        /** @example 5000 */
        gap_ms?: number;
        /** @example 21000 */
        pit_loss_ms?: number;
        /** @example GREEN */
        track_status?: string;
        rainfall?: boolean;
      };
    };
    responses: {
      /** @description Prediction produced successfully. */
      200: {
        content: {
          "application/json": components["schemas"]["CausalPredictionOut"];
        };
      };
    };
  };
}
